version: "3.1"

services:
  postgres:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_DB=$DATABASE
    restart: always
    env_file:
      - ".env"
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/posrgresql

  telegram_bot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - postgres

networks:
  botnet:
    driver: bridge
