version: "3.1"

services:
  db:
    container_name: database
    image: postgres:latest
    environment:
      PGPASSWORD: $PGPASSWORD
    restart: always
    env_file:
      - ".env"
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/posrgresql

  telegram_bot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - db

networks:
  botnet:
    driver: bridge